name: deploy-app
on:
  push:
    branches:
      - main:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate deployment
        run: echo "Deployment successful!"
